### PR TITLE
fix(devices): add special-case recognition of Firefox-iOS

### LINKED ISSUE #1555: node-uap fails to parse Firefox for iOS service user-agent
The syncing component of Firefox for iOS sends a custom user-agent string like this:

```
Firefox-iOS-FxA/5.3 (Firefox)
```

The node-uap library is not able to parse it.  So when we create placeholder device records for Firefox on iOS, they wind up looking like this:

screen shot 2016-11-17 at 13 46 53

Note that it (a) has an ugly raw user-string as its display name, and (b) is shown as a desktop device rather than mobile.

Can we add an additional parsing rule to catch this case?  The device-registration-capable version of Firefox for iOS has not shipped yet, and users will be seeing this in the wild until it does.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1555.

Firefox-iOS is showing up with ugly user agent strings in the device view. This adds a test to recognise them and return appropriate parsed data instead.

I took the simplest approach of ignoring the Firefox version in the regex here. We could also add a match group to pull that out and return an appropriate `uaBrowserVersion` too if it's preferable. But I thought that was probably unnecessary in light of #1556, which suggests dropping the browser version. And the less specific regex may (or may not) be more robust?

@vladikoff r?

### CODE REVIEW

**Comment by philbooth** [comment]
Screenshot of the updated devices view with this change:

Screenshot showing a correctly parsed Firefox-iOS device

**Comment by philbooth** [comment]
Hmm, tests are failing travis but fine locally. Investigating.

**Comment by philbooth** [comment]
> ...tests are failing in CI...

My bad, I wasn't based off latest `master`.

File: lib/userAgent.js [hunk 1]
```diff
@@ -27,6 +27,8 @@ var MOBILE_OS_FAMILIES = {
 
 var ELLIPSIS = '\u2026'
 
+const OLD_FIREFOX_IOS_USER_AGENT = /^Firefox-iOS-FxA/
```
Comment (philbooth) [inline lib/userAgent.js]: > ...this is not an "old" UA.

Oh, I didn't realise that, sorry. Will fix.

> ...maybe that is why we are getting Android "tablets" in the initial device view.

I think you're on to something here, testing it out now.

**Comment by philbooth** [comment]
@vladikoff, I've updated this to use a better name for the regex, pull the browser version out of the user agent and also handle the Android version. I haven't done anything about the Android tablet icon because I don't see a way to make it work sanely, but I could just force it to `mobile` in this case if we think that's better.

Screenshot of the Android user agent:

Screenshot showing an Android user agent in the devices view

Updated screenshot of the iOS user agent:

Screenshot showing an iOS user agent in the devices view

**Comment by vladikoff** [comment]
@philbooth this is awesome! Thanks so much 👍
