### PR TITLE
fix(log): add mozlog fmt properly

### LINKED ISSUE #1138: Add configurable "fmt: 'pretty'" to mozlog when server is running in dev mode
Example from oauth: https://github.com/mozilla/fxa-oauth-server/blob/master/config/dev.json#L93

## Without fmt:pretty
```
  fxa-auth-server git:(sqs-verify-email) ✗ npm start

> fxa-auth-server@1.51.1 start /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server
> NODE_ENV=dev scripts/start-local.sh 2>&1

{"Timestamp":1450292098997000000,"Logger":"fxa-auth-server","Type":"","Severity":6,"Pid":92273,"EnvVersion":"2.0","Fields":{"env":"dev","log":"{\"level\":\"info\"}","publicUrl":"http://127.0.0.1:9000","domain":"127.0.0.1:9000","secretKeyFile":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/config/secret-key.json","publicKeyFile":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/config/public-key.json","trustedJKUs":"[\"http://127.0.0.1:8080/.well-known/public-keys\",\"http://127.0.0.1:10139/.well-known/public-keys\"]","db":"{\"backend\":\"httpdb\"}","httpdb":"{\"url\":\"http://127.0.0.1:8000\"}","listen":"{\"host\":\"127.0.0.1\",\"port\":9000}","customsUrl":"none","contentServer":"{\"url\":\"http://127.0.0.1:3030\"}","smtp":"{\"api\":{\"host\":\"127.0.0.1\",\"port\":9001},\"host\":\"127.0.0.1\",\"port\":9999,\"secure\":false,\"sender\":\"Firefox Accounts <no-reply@lcip.org>\",\"verificationUrl\":\"http://127.0.0.1:3030/v1/verify_email\",\"passwordResetUrl\":\"http://127.0.0.1:3030/v1/complete_reset_password\",\"accountUnlockUrl\":\"http://127.0.0.1:3030/v1/complete_unlock_account\",\"initiatePasswordResetUrl\":\"http://127.0.0.1:3030/reset_password\",\"syncUrl\":\"https://www.mozilla.org/en-US/firefox/sync/\",\"androidUrl\":\"https://www.mozilla.org/en-US/firefox/android/\",\"iosUrl\":\"https://www.mozilla.org/en-US/firefox/ios/\",\"supportUrl\":\"https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account\",\"redirectDomain\":\"firefox.com\",\"resendBlackoutPeriod\":0,\"initiatePasswordChangeUrl\":\"http://127.0.0.1:3030/settings/change_password\"}","maxEventLoopDelay":0,"scrypt":"{\"maxPending\":0}","i18n":"{\"defaultLanguage\":\"en\",\"supportedLanguages\":[\"az\",\"bg\",\"cs\",\"cy\",\"da\",\"de\",\"dsb\",\"en\",\"en-GB\",\"es\",\"es-AR\",\"es-CL\",\"et\",\"fa\",\"ff\",\"fr\",\"fy\",\"he\",\"hi-IN\",\"hsb\",\"hu\",\"it\",\"ja\",\"kk\",\"ko\",\"lt\",\"nl\",\"pa\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"rm\",\"ru\",\"sk\",\"sl\",\"sq\",\"sr\",\"sr-LATN\",\"sv\",\"sv-SE\",\"tr\",\"uk\",\"zh-CN\",\"zh-TW\"]}","tokenLifetimes":"{\"accountResetToken\":900000,\"passwordForgotToken\":3600000,\"passwordChangeToken\":900000}","verifierVersion":0,"snsTopicArn":"disabled","bounces":"{\"region\":\"\",\"bounceQueueUrl\":\"\",\"complaintQueueUrl\":\"\"}","verificationReminder":"{\"queueRegion\":\"us-west-2\",\"queueUrl\":\"https://sqs.us-west-2.amazonaws.com/927034868273/fxa-local-dev-verification-reminder-v1\",\"queueRate\":1}","useHttps":false,"keyPath":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/key.pem","certPath":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/cert.pem","lockoutEnabled":true,"oauth":"{\"url\":\"http://localhost:9010\",\"email\":false}","openIdProviders":"[]","statsd":"{\"enabled\":true,\"host\":\"localhost\",\"port\":8125,\"sample_rate\":1}","corsOrigin":"*","isProduction":false,"openIdVerifyUrl":"http://127.0.0.1:9000/v1/account/openid/login"}}
{"Timestamp":1450292099064000000,"Logger":"fxa-auth-db-server","Type":"bin.server.start","Severity":2,"Pid":92272,"EnvVersion":"2.0","Fields":{"message":"listen EADDRINUSE 127.0.0.1:8000"}}
{"Timestamp":1450292099757000000,"Logger":"fxa-auth-server","Type":"uncaughtException","Severity":0,"Pid":92273,"EnvVersion":"2.0","Fields":{"code":"MODULE_NOT_FOUND"}}
{"Timestamp":1450292099757000000,"Logger":"fxa-auth-server","Type":"","Severity":0,"Pid":92273,"EnvVersion":"2.0","Fields":{"code":"MODULE_NOT_FOUND"}}
scripts/start-local.sh: line 10: kill: (92271) - No such process
scripts/start-local.sh: line 11: kill: (92272) - No such process

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! fxa-auth-server@1.51.1 start: `NODE_ENV=dev scripts/start-local.sh 2>&1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-auth-server@1.51.1 start script 'NODE_ENV=dev scripts/start-local.sh 2>&1'.
npm ERR! This is most likely a problem with the fxa-auth-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=dev scripts/start-local.sh 2>&1
npm ERR! You can get their info via:
npm ERR!     npm owner ls fxa-auth-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/npm-debug.log
```

## With (get a stack trace)

```
➜  fxa-auth-server git:(sqs-verify-email) ✗ npm start

> fxa-auth-server@1.51.1 start /Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server
> NODE_ENV=dev scripts/start-local.sh 2>&1

fxa-auth-server.INFO: undefined {"env":"dev","log":{"level":"info"},"publicUrl":"http://127.0.0.1:9000","domain":"127.0.0.1:9000","secretKeyFile":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/config/secret-key.json","publicKeyFile":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/config/public-key.json","trustedJKUs":["http://127.0.0.1:8080/.well-known/public-keys","http://127.0.0.1:10139/.well-known/public-keys"],"db":{"backend":"httpdb"},"httpdb":{"url":"http://127.0.0.1:8000"},"listen":{"host":"127.0.0.1","port":9000},"customsUrl":"none","contentServer":{"url":"http://127.0.0.1:3030"},"smtp":{"api":{"host":"127.0.0.1","port":9001},"host":"127.0.0.1","port":9999,"secure":false,"sender":"Firefox Accounts <no-reply@lcip.org>","verificationUrl":"http://127.0.0.1:3030/v1/verify_email","passwordResetUrl":"http://127.0.0.1:3030/v1/complete_reset_password","accountUnlockUrl":"http://127.0.0.1:3030/v1/complete_unlock_account","initiatePasswordResetUrl":"http://127.0.0.1:3030/reset_password","syncUrl":"https://www.mozilla.org/en-US/firefox/sync/","androidUrl":"https://www.mozilla.org/en-US/firefox/android/","iosUrl":"https://www.mozilla.org/en-US/firefox/ios/","supportUrl":"https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account","redirectDomain":"firefox.com","resendBlackoutPeriod":0,"initiatePasswordChangeUrl":"http://127.0.0.1:3030/settings/change_password"},"maxEventLoopDelay":0,"scrypt":{"maxPending":0},"i18n":{"defaultLanguage":"en","supportedLanguages":["az","bg","cs","cy","da","de","dsb","en","en-GB","es","es-AR","es-CL","et","fa","ff","fr","fy","he","hi-IN","hsb","hu","it","ja","kk","ko","lt","nl","pa","pl","pt","pt-BR","pt-PT","ro","rm","ru","sk","sl","sq","sr","sr-LATN","sv","sv-SE","tr","uk","zh-CN","zh-TW"]},"tokenLifetimes":{"accountResetToken":900000,"passwordForgotToken":3600000,"passwordChangeToken":900000},"verifierVersion":0,"snsTopicArn":"disabled","bounces":{"region":"","bounceQueueUrl":"","complaintQueueUrl":""},"verificationReminder":{"queueRegion":"us-west-2","queueUrl":"https://sqs.us-west-2.amazonaws.com/927034868273/fxa-local-dev-verification-reminder-v1","queueRate":1},"useHttps":false,"keyPath":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/key.pem","certPath":"/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/cert.pem","lockoutEnabled":true,"oauth":{"url":"http://localhost:9010","email":false},"openIdProviders":[],"statsd":{"enabled":true,"host":"localhost","port":8125,"sample_rate":1},"corsOrigin":"*","isProduction":false,"openIdVerifyUrl":"http://127.0.0.1:9000/v1/account/openid/login"}
{"Timestamp":1450291951382000000,"Logger":"fxa-auth-db-server","Type":"bin.server.start","Severity":2,"Pid":90811,"EnvVersion":"2.0","Fields":{"message":"listen EADDRINUSE 127.0.0.1:8000"}}
fxa-auth-server.CRITICAL: uncaughtException Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/verification_reminder.js:7:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/routes/account.js:29:21)
    at module.exports (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/routes/index.js:27:37)
    at DB.connect.done.log.error.op (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/bin/key_server.js:77:52)
    at tryCatcher (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
fxa-auth-server.CRITICAL: undefined Error: Cannot find module '../../config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/verification_reminder.js:7:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/routes/account.js:29:21)
    at module.exports (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/lib/routes/index.js:27:37)
    at DB.connect.done.log.error.op (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/bin/key_server.js:77:52)
    at tryCatcher (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/vladikoff/mozilla/fxa-local-dev/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1138

### CODE REVIEW

**Comment by vladikoff** [comment]
Github is being weird, please see patch here: https://github.com/mozilla/fxa-auth-server/pull/1143.patch

@dannycoates @rfk r?

File: test/local/log_tests.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ test(
     t.equal(mocks.mozlog.config.callCount, 1, 'mozlog.config was called once')
     var args = mocks.mozlog.config.args[0]
     t.equal(args.length, 1, 'mozlog.config was passed one argument')
-    t.equal(Object.keys(args[0]).length, 3, 'mozlog.config argument had with three properties')
+    t.equal(Object.keys(args[0]).length, 4, 'mozlog.config argument had with three properties')
```
Comment (rfk) [inline test/local/log_tests.js]: s/three/four/ in the test description, but otherwise LGTM
