### PR TITLE
fix(node 8 and scrypt-hash): removed support for node 8 and scrypt-hash

### LINKED ISSUE #2958: Remove support for node 8, support 10+
We still support node 8 but our Docker images are now built using node 10. Let's drop support for node 8 and remove node-scrypt from the devDependencies list.

### PR DESCRIPTION
**Pull request by farhan787**
fixes #2958

### CODE REVIEW

File: lib/crypto/scrypt.js [hunk 1]
```diff
@@ -56,12 +50,7 @@ module.exports = function(log, config) {
       if (scrypt.numPending > scrypt.numPendingHWM) {
         scrypt.numPendingHWM = scrypt.numPending
       }
-      if (scryptHash) {
-        scryptHash(input, salt, N, r, p, len, (err, hash) => {
-          scrypt.numPending -= 1
-          return err ? d.reject(err) : d.resolve(hash.toString('hex'))
-        })
-      } else if (crypto.scrypt) {
+      if (crypto.scrypt) {
```
Comment (philbooth) [inline lib/crypto/scrypt.js]: I think you can delete this `if` and the trailing `else` too, `crypto.scrypt` will always be available.

**Comment by farhan787** [comment]
@philbooth thanks for correcting me and making it better.

**Comment by farhan787** [comment]
Your most welcome @philbooth
