### PR TITLE
fix(emails): Only send email notifications to verified secondary emails

### LINKED ISSUE #1887: Only send to verified secondary emails
Currently, informational (password charge, new sign-in, password reset) emails are sent to all secondary emails, regardless of verification state. We should only send to `verified` emails.

### PR DESCRIPTION
**Pull request by vbudhram**
This PR updates how we handle sending email notifications to secondary email. Previously, we were sending all to emails, verified nor not. With this change we only send to verified emails.

Fixes #1887 

@rfk r? / @mozilla/fxa-devs

### CODE REVIEW

File: lib/senders/index.js [hunk 1]
```diff
@@ -46,15 +46,6 @@ module.exports = function (log, config, error, bounces, translator, sender) {
       }, [])
     }
 
-    function getSecondaryEmails(emails) {
```
Comment (philbooth) [inline lib/senders/index.js]: Tangential but while you're in here removing this, maybe `getVerifiedSecondaryEmails` could be simplified to use `Array.filter` instead of `Array.reduce`?

File: lib/senders/index.js [hunk 2]
```diff
@@ -160,7 +151,7 @@ module.exports = function (log, config, error, bounces, translator, sender) {
       },
       sendPasswordChangedNotification: function (emails, account, opts) {
         var primaryEmail = account.email
-        var ccEmails = getSecondaryEmails(emails)
+        var ccEmails = getVerifiedSecondaryEmails(emails)
```
Comment (philbooth) [inline lib/senders/index.js]: Also tangential: Seems like there's a lot of common boilerplate in these methods. Worth opening an issue to fix it?

Comment (philbooth) [inline lib/senders/index.js]: s/a lot/some/

**Comment by philbooth** [comment]
LGTM! r+

File: lib/senders/index.js (hunk 2 above)
Comment (vbudhram) [inline lib/senders/index.js]: Looks like we have a running list of items in https://github.com/mozilla/fxa-auth-server/issues/1725, appending it.
