### PR TITLE
fix(push): Allow device connection push messages for Firefox iOS >= 9.0

### LINKED ISSUE #2083: Allow device connected/disconnected push messages for iOS >= 9.0
Newer versions of Firefox for iOS support these additional push messages, so we'll need to tweak out UA-sniffing to to allow them to be sent.

### PR DESCRIPTION
**Pull request by rfk**
Fixes #2083, but WIP while I do a bit of mucking around with it

### CODE REVIEW

**Comment by rfk** [comment]
OK, tests added, I think this one is ready.  @vbudhram r?

File: lib/push.js [hunk 1]
```diff
@@ -171,6 +171,40 @@ module.exports = function (log, db, config) {
...
+   * if they receive an unsupported message type.  Filter out
+   * devices that we know won't respond well to the given command.
+   *
+   * @param {String} command
+   * The command from the push message payload
+   * @param {Device[]} devices
+   * The list of devices to which to send the push.
+   */
+  function filterSupportedDevices(command, devices) {
+    var minVersion
```
Comment (vbudhram) [inline lib/push.js]: nit: `miniOsVersion` would be a little more clear.

File: lib/push.js [hunk 2]
```diff
@@ -171,6 +171,40 @@ module.exports = function (log, db, config) {
...
+    default:
+      minVersion = Infinity
+    }
+    return devices.filter(function(device) {
+      var deviceOS = device.uaOS && device.uaOS.toLowerCase()
+      if (deviceOS !== 'ios') {
+        return true
+      }
+      var deviceVersion = device.uaBrowserVersion ? parseFloat(device.uaBrowserVersion) : 0
+      return deviceVersion >= minVersion
```
Comment (vbudhram) [inline lib/push.js]: Would it make sense to add some logging here to see how many iOS devices are being sent or not sent notifications? We could potentially use that data to know when X% of users have migrated to proper version and can remove version check? Or is there another way to get this data?

File: test/local/push.js [hunk 3]
```diff
@@ -316,6 +316,70 @@ describe('push', () => {
   )
 
   it(
+    'sendPush pushes to ios >=9.0 devices if it is triggered with a "device connected" command',
+    () => {
+      var data = Buffer.from(JSON.stringify({command: 'fxaccounts:device_connected'}))
```
Comment (vbudhram) [inline test/local/push.js]: I vaguely remember a conversation where we said new code would try to use ES6 and const/let where possible?

File: lib/push.js (hunk 1 above)
Comment (philbooth) [reply lib/push.js]: Please not `miniOsVersion`! That reads like "mini-OS version".

Comment (vbudhram) [reply lib/push.js]: Heh, yea didn't notice that until you pointed it out. My line of thinking was since this function could potentially filter any device from any OS it might be good to be specific in variable name here.

Maybe `minimumiOsVersion`?

Comment (philbooth) [reply lib/push.js]: If the `ios` part has to be included I'd ignore Apple's upper/lowercase whimsy entirely. And for the prefix I think `required` > `minimum` > `min`. So `requiredIosVersion` is my vote, if this is a democracy.

**Comment by rfk** [comment]
updated to address nits, will merge when green
