### PR TITLE
fix(unblock): Fix db.createUnblockCode - code generation is async.

### LINKED ISSUE #1531: "Request path contains unescaped characters" error calling /account/login/send_unblock_code
This is in fxa-ci.dev.lcip.org, whenever an unblock code is sent the following exception appears in the logs:

```
{"Timestamp":1477646328499000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":23288,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,"rid":"1477646328473:ip-172-31-44-29:23288:iutkgusm:10001","path":"/auth/v1/account/login/send_unblock_code","lang":"en,es;q=0.8,de;q=0.6,es-AR;q=0.4,en-US;q=0.2","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0","remoteAddressChain":"[\"95.85.19.180\",\"172.31.16.75\",\"127.0.0.1\"]","t":26,"uid":"00","email":"stomlinson@mozilla.com","stack":"TypeError: Request path contains unescaped characters.\n    at new ClientRequest (_http_client.js:50:11)\n    at Object.exports.request (http.js:31:10)\n    at Endpoint.request (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:211:23)\n    at RequestSet.doRequest (/data/fxa-auth-server/node_modules/poolee/lib/request_set.js:89:7)\n    at Function.RequestSet.request (/data/fxa-auth-server/node_modules/poolee/lib/request_set.js:84:6)\n    at Pool.request (/data/fxa-auth-server/node_modules/poolee/lib/pool.js:147:14)\n    at Pool.request (/data/fxa-auth-server/lib/pool.js:37:15)\n    at Pool.put (/data/fxa-auth-server/lib/pool.js:80:15)\n    at DB.createDevice.random.then.id.then.DB.createUnblockCode.uid [as createUnblockCode] (/data/fxa-auth-server/lib/db.js:816:22)\n    at createUnblockCode (/data/fxa-auth-server/lib/routes/account.js:1694:23)\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/data/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/data/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/data/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/data/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}}
```

I added a little logging to `pool.js` to print the request info:

```
{"Timestamp":1477646328497000000,"Logger":"fxa-auth-server","Type":"console","Severity":4,"Pid":23288,"EnvVersion":"2.0","Fields":{"op":"console","message":"method PUT path /account/adce1591df1b4146a45fb72b6ceb68af/unblock/[object Promise] data undefined"}}
```

It seems to be trying to send a promise as the unblock code.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
db.createUnblockCode called UnblockCode synchronously, but it's now
asynchronous.

fixes #1531

@philbooth since you are here, or @seanmonstar if @philbooth doesn't have time!

### CODE REVIEW

File: test/remote/db_tests.js [hunk 1]
```diff
@@ -621,6 +623,49 @@ test(
...
+        },
+        function (err) {
+          t.equal(err.errno, 127, 'consumeUnblockCode() fails with the correct error code')
+          var msg = 'Error: Invalid unblock code';
+          t.equal(msg, '' + err, 'consumeUnblockCode() fails with the correct message')
+        }
+      )
+      .then(function() {
+        return db.consumeUnblockCode(ACCOUNT.uid, unblockCode);
+      })
```
Comment (philbooth) [inline test/remote/db_tests.js]: I'd insert a rejection handler at this point, otherwise a rejection from the valid call will fall down to line 659 where you test the rejection that you're expecting. Or have I read the logic wrong?

**Comment by philbooth** [comment]
Fix looks good! I've left one inline comment about the tests, but otherwise I am r+.

File: test/remote/db_tests.js (hunk 1 above)
Comment (shane-tomlinson) [inline test/remote/db_tests.js]: Thanks for pointing that out

**Comment by seanmonstar** [comment]
:cry: :sob:
