### PR TITLE
fix(logging): silence spurious "missing token" error noise

### LINKED ISSUE #1595: seeing a lot of '"op":"metricsContext.gather","err":"Error: Missing token"' in stage. Expected?
Just filing this to get an opinion on whether this is expected. Seeing a lot of '"op":"metricsContext.gather","err":"Error: Missing token"' in stage. 

@rfk, @philbooth ?

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1595.

The "missing token" error generates a lot of log noise because it occurs in legitimate scenarios when trying to gather metrics context data speculatively, from `log.notifyAttachedServices` and `log.flowEvent`.

We were already silencing it in `metricsContext.clear` and actually, due to the above, I think we should silence it in `gather` too. Doing this means `getToken` no longer needs to `throw`, which pleases me because it was only throwing for flow control anyway (my fault).

I also think our logging elsewhere is sufficient to cover any genuine issues relating to missing token data.

@vbudhram r?

### CODE REVIEW

File: lib/metrics/context.js [hunk 1]
```diff
@@ -104,18 +103,20 @@ module.exports = function (log, config) {
    * @param data target object
    */
   function gather (data) {
-    const metadata = this.payload && this.payload.metricsContext
     let token
 
     return P.resolve()
       .then(() => {
+        const metadata = this.payload && this.payload.metricsContext
```
Comment (philbooth) [inline lib/metrics/context.js]: I moved this local to the inner scope to avoid any confusion when a later scope re-uses the same variable name.

File: lib/error.js [hunk 2]
```diff
@@ -31,7 +31,7 @@ var ERRNO = {
   REQUEST_BLOCKED: 125,
   ACCOUNT_RESET: 126,
   INVALID_UNBLOCK_CODE: 127,
-  MISSING_TOKEN: 128,
+  // MISSING_TOKEN: 128,
```
Comment (vbudhram) [inline lib/error.js]: Doesn't look like this is used anywhere, did you intend to keep it around in case we bring back missing token somewhere else?

Comment (philbooth) [inline lib/error.js]: This is a convention that we already follow in this file, if you look a bit further up at the lines for `ACCOUNT_LOCKED` and `ACCOUNT_NOT_LOCKED`.

Once retired, we don't want to re-use old error numbers for new reasons because it may make diagnosing problems in the logs tricky around the boundaries.

**Comment by philbooth** [comment]
> You mentioned that we have logging elsewhere to cover any legit issues with tokens is this `calculateFlowSignatureBytes` in metrics lib?

Actually I was thinking about the request-level logging. It's kind of tautological, but missing tokens in `metricsContext.gather` are not an error on endpoints where tokens are either optional or unrequired. So Hapi's validation layer would already be kicking in and covering us in the cases where it is a problem.

The only time I could see one of these "missing token" errors being genuine is if a token gets sent to an endpoint but then our own code removes the token mistakenly for some reason. The chances of this imaginary problem happening seem unlikely enough that it's not worth paying the price of the real problem we have, which is log noise.

**Comment by philbooth** [comment]
Thanks @vbudhram!
