### PR TITLE
fix(bypass): Don't bypass sign-in confirmation for forced emails

### LINKED ISSUE #1547: IP Profiling ignores sign-in confirmation force email
Per https://github.com/mozilla/fxa-content-server/issues/4401#issuecomment-260605550, IP Profiling should not allow emails that are explicitly required to go through sign-in confirmation, to bypass it if accessing from same IP.

### PR DESCRIPTION
**Pull request by vbudhram**
For consideration, this does not bypass sign-in confirmation when it is specified by a forced email.

- [x] Don't bypass sign-in confirmation
- [x] Rename `enabledEmailAddresses` to `forcedEmailAddresses`
- [ ] ~~Rename `canBypassSiginConfirmation` to `isIpProfilingEnabledForUser`~~

Fixes #1547

### CODE REVIEW

File: lib/features.js [hunk 1]
```diff
@@ -110,18 +110,21 @@ module.exports = config => {
...
+        return false
+      }
 
       // IP Profiling sets bypass to true if this user has verified a session
       // within the past day from this ip address.
       let ipProfilingEnabled = securityHistory.enabled && securityHistory.ipProfiling &&
         securityHistory.ipProfiling.enabled
       if (ipProfilingEnabled && verified && recency === 'day') {
-        bypass = true
+        return true
```
Comment (seanmonstar) [inline lib/features.js]: It's fine as is, but I just noticed, this `if` could be removed, and just end the function with `return ipProfilingEnabled && verified && recency === 'day'`

**Comment by vbudhram** [comment]
@seanmonstar Made some changes that I thought warrant another look over, r?

**Comment by vbudhram** [comment]
@seanmonstar Thanks!

**Comment by shane-tomlinson** [comment]
👍 Thanks @seanmonstar and @vbudhram!
