### PR TITLE
fix(push): add support for dev and stage push servers

### LINKED ISSUE #1799: Accept dev push server URLs
When developing new push servers, clients sometimes use `https://updates-autopush.dev.mozaws.net/` as their push server rather than the production instance.  It seems harmless for us to accept this as a valid push endpoint URL, even in production, because it's a mozilla-controlled URL and we know what's running on it.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1799 

@vbudhram r? 

#RegexFridays

### CODE REVIEW

File: test/remote/device_tests.js [hunk 1]
```diff
@@ -286,6 +286,116 @@ describe('remote device', function() {
...
+                function (err) {
+                  assert.fail(err, 'request should have worked')
+                }
+              )
+          })
+    }
+  )
+
+  it(
+    'update device works with stage servers',
```
Comment (vbudhram) [inline test/remote/device_tests.js]: Should this be `update device works with dev servers`, callback specifies `dev`.

Comment (vladikoff) [inline test/remote/device_tests.js]: ty!
