### PR TITLE
fix(key-data): fix key-data endpoint for fresh accounts

### LINKED ISSUE #2908: FxA Sign up fails with "Stale Authentication Timestamp"
Ref: https://github.com/mozilla-mobile/reference-browser/issues/569

We can sign in but not sign up!

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2908
Fixes https://github.com/mozilla-mobile/reference-browser/issues/569

### CODE REVIEW

File: fxa-oauth-server/test/api.js [hunk 1]
```diff
@@ -2614,6 +2614,19 @@ describe('/v1', function() {
             assert.equal(Object.keys(res.result).length, 0, 'no scoped keys');
           });
       });
+
+      it('correctly verifies stale authAt', () => {
```
Comment (rfk) [inline fxa-oauth-server/test/api.js]: nit: the name of this test seems confusing to me, suggesting that it verifies an authentication that it actually stale.  Something like "correctly handles authAt timestamp for newly-created accounts" might prevent future confusion.

Comment (vladikoff) [reply fxa-oauth-server/test/api.js]: radical!

**Comment by vladikoff** [comment]
Rebased for train-130
