### PR TITLE
fix(server): make geo data lazily available on the request

### LINKED ISSUE #2015: Eliminate redundant calls to getGeoData
Arising from https://github.com/mozilla/fxa-auth-server/pull/1993#discussion_r128997049, I notice that we can eliminate some duplicate calls to `getGeoData`. Just inside `/account/login` it is called on three separate occasions, for instance.

We should tidy these up so that we're not doing more work on the server than we need to. We can also lean on the data stored in redis, if it's available. Maybe these properties should be made available on the `SessionToken` object so that people are less likely to duplicate the effort in the future.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #2015.

This didn't turn out quite as nicely as the user-agent stuff because `getGeoData` is an async call, so we need to consider what to do if it is accessed before the promise has resolved. Ultimately I decided to expose the raw promise as `request.app.geo` because that places the least burden on consuming code.

Some alternatives I discounted were:

* Make the property non-lazy and set it in `lib/server` as soon as `getGeoData` resolves. This would force consuming code to check the value before use and take appropriate action itself if unset, possibly including a duplicate call to `getGeoData`.

* Expose dual `request.app.geo.value` and `request.app.geo.promise` properties. Again it forces consumers to include ugly checks, for the limited benefit of eliminating a call to `.then`.

All told it's both simpler and more idiomatic for consuming code to just always use `request.app.geo.then()` and let promises handle the complexity of waiting until data is available. It's what they're designed for, after all.

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by philbooth** [comment]
> * Make the property non-lazy and set it in `lib/server` as soon as `getGeoData` resolves. This would force consuming code to check the value before use and take appropriate action itself if unset, possibly including a duplicate call to `getGeoData`.

There's another variation on this that I also discounted, which is to expose it non-lazily in `lib/server` and not call `reply.continue()` until it has resolved. That adds extra latency (and server work) for the geo-lookup to every request, even ones that go on to fail authentication or validation checks.

File: test/local/server.js [hunk 1]
```diff
@@ -162,13 +178,15 @@ describe('lib/server', () => {
...
+                'user-agent': 'Firefox-Android-FxAccounts/34.0a1 (Nightly)',
+                'x-forwarded-for': ' 194.12.187.0 , 194.12.187.0 '
               },
               method: 'POST',
               url: '/account/create',
               payload: {
                 features: [ 'signinCodes' ]
-              }
+              },
+              remoteAddress: '194.12.187.0'
```
Comment (vbudhram) [inline test/local/server.js]: How likely is it for the ip address to be released and generate a new location? I believe `63.245.221.32` is an address that is owned by Mozilla and in Mountain View. Is there another ip we could potentially use and not Mountain View based? 

cc @jbuck

Comment (philbooth) [reply test/local/server.js]: I chose it for exactly this reason, because it's unlikely to change. The whole `194.12.187` block is owned by CERN. I figure they're not going anywhere.

Comment (shane-tomlinson) [reply test/local/server.js]: > The whole 194.12.187 block is owned by CERN. I figure they're not going anywhere.

Hopefully they don't get swallowed by a self-created black hole from the LHC.
