### PR TITLE
fix(signin): Add keyFetchToken verification state support

### LINKED ISSUE #1287: Add KeyFetchToken verification state support
This is a follow up issue to add support for KeyFetchToken verification states. This ability was added to [fxa-auth-mysql-db](https://github.com/mozilla/fxa-auth-db-mysql/pull/138) and the auth-server needs to be updated to utilize these states.

### PR DESCRIPTION
**Pull request by vbudhram**
This PR adds support for account verification status check via `/account/keys`.

- [x]  `/account/keys` checks status of keyFetchToken and return `Unverified account` if not verified
- [x] `/account/login` creates keyFetchToken with same verification state as sessionToken
- [x] `/password/change/start` correctly handles keyFetchTokens

Fixes #1287

### CODE REVIEW

**Comment by vbudhram** [comment]
Hey @rfk, finally got part of this working. For the life of me I could not get this to work properly when pointing to a localhost version of FxA from within the Firefox browser in Android. However, when using a [deployed](https://vbudhramsignin.dev.lcip.org) version it works as expected. 

Would you mind pointing your android emulator/device to https://vbudhramsignin.dev.lcip.org and give it a spin?

File: config/index.js [hunk 1]
```diff
@@ -417,7 +417,7 @@ var conf = convict({
   signinConfirmation: {
     enabled: {
       doc: 'enable signin confirmation',
-      default: false,
+      default: true,
```
Comment (rfk) [inline config/index.js]: Just noting that we need to be careful about merging this on-by-default config to master...

File: lib/routes/account.js [hunk 2]
```diff
@@ -477,7 +478,8 @@ module.exports = function (
                     uid: emailRecord.uid,
                     kA: emailRecord.kA,
                     wrapKb: wrapKb,
-                    emailVerified: emailRecord.emailVerified
+                    emailVerified: emailRecord.emailVerified,
+                    tokenVerificationId: doSigninConfirmation ? tokenVerificationId : undefined
```
Comment (rfk) [inline lib/routes/account.js]: In addition to these two changes where we *do* set a `tokenVerificationId`, I think it would be worthwhile to update the password-change-related endpoints with a comment to explain why we're *deliberately not* setting one.  If we don't get back to revisiting those for a while, our future selves will thank us.

**Comment by vbudhram** [comment]
@rfk You were correct about the config values being off. Here are the correct values to get Sync and sign-in confirmation working in Fennec.

* Change the following `about:config` values for Fennec
  * identity.fxaccounts.auth.uri = https://vbudhramsignin.dev.lcip.org/auth/v1
  * identity.fxaccounts.remote.oauth.uri = https://oauth-vbudhramsignin.dev.lcip.org
  * identity.fxaccounts.remote.profile.uri = https://vbudhramsignin.dev.lcip.org/profile
  * identity.sync.tokenserver.uri = https://vbudhramsignin.dev.lcip.org

This PR will correctly enable sign-in confirmation for Android devices, however iOS has some issues. Particularly not staying on the `Confirm sign-in page` and popping the view to settings page. My gut feeling is to not block this PR because of iOS, but rather work that in another PR. Thoughts?

**Comment by rfk** [comment]
The code here looks great, I will take it for a bit of spin before merge.

File: lib/db.js [hunk 3]
```diff
@@ -345,6 +345,23 @@ module.exports = function (
...
+          return KeyFetchToken.fromId(id, data)
+        },
+        function (err) {
+          if (isNotFoundError(err)) {
+            err = error.invalidToken()
+          }
+          throw err
+        }
+      )
+  }
```
Comment (rfk) [inline lib/db.js]: @vbudhram you need to also update `createKeyFetchToken` in this file, to accept the new `tokenVerificationId` parameter.  Otherwise it just silently ignores it and all keyFetchTokens are created verified.

**Comment by rfk** [comment]
With the one mentioned fix to `db.createKeyFetchToken`, I was able to successfully signin on an Android device, and it correctly walked me through the confirmation flow:

* it polled /account/keys, got an "unverified account" error, and didn't attempt to sync
* when I confirmed the signin, I was able to go into "sync now" and it synced successfully

So I think this is looking good!

There was some weirdness with signing out and signing back in again, but I suspect it to be a bug on the android side.  Next, I will see if I can try this out on an iOS device...

**Comment by rfk** [comment]
> Next, I will see if I can try this out on an iOS device...

I'm pleased to report, this seemed to work similarly.  It polled /account/keys and got a "400 unverified account", went into the "verify your email" UI state, and when I did confirm the sign-in via email it all seemed to sync as expected.

Unfortunately, as you noted @vbudhram it does *not* show the "confirm this sign-in screen", instead closing the content-server page as soon as it receives the login notification event.  I'm not sure there's much we can do about that if it's behaviour baked into the client itself.

File: config/index.js [hunk 4]
```diff
@@ -436,7 +436,9 @@ var conf = convict({
         'fx_firstrun_v2',
         'fx_desktop_v1',
         'fx_desktop_v2',
-        'fx_desktop_v3'
+        'fx_desktop_v3',
+        'fx_ios_v1',
```
Comment (rfk) [inline config/index.js]: According to content-server, there's also an `fx_ios_v2` context that we should probably add to this list.

**Comment by rfk** [comment]
Good stuff @vbudhram, r+

**Comment by rfk** [comment]
(also note, I'm squashing down to a single commit for the final merge)

**Comment by rfk** [comment]
@vbudhram I squashed this and added `fx_ios_v2` context, if the result seems sane please merge at your convenience.

**Comment by shane-tomlinson** [comment]
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1289480 is for the iOS issue where it takes over w/o displaying the "confirm this sign in" screen.
