### PR TITLE
fix(release): on `grunt version(:patch?), bump both ./package.json and fxa-oauth-server/package.json

### LINKED ISSUE #2720: [oauth] fxa-oauth-server v1.124.3 didn't pick up semver from its package.json
curl -s 'https://oauth.accounts.firefox.com/__version__'
```
{
  "version": "1.124.0",
  "commit": "dcc537a9bafae9f5eba9a8bba975e3365858f282",
  "source": "https://github.com/mozilla/fxa-oauth-server"
}
```

```
$ cd fxa-auth-server
$ git log --oneline -1 v1.124.3
dcc537a9 (tag: v1.124.3, origin/train-124) Release v1.124.3
```

https://github.com/mozilla/fxa-auth-server/commit/dcc537a9bafae9f5eba9a8bba975e3365858f282

So `dcc537a` is the release commit for `v1.124.3`, but while `__version__` shows that sha, the semver is `1.124.0`.

The `version.json` inside the container does read 
```
{"version":{"hash":"dcc537a9bafae9f5eba9a8bba975e3365858f282",
"version":"v1.124.3","source":"https://github.com/mozilla/fxa-oauth-server",
"build":"https://circleci.com/gh/mozilla/fxa-auth-server/3688"}}
```

### PR DESCRIPTION
**Pull request by jrgm**
Fixes #2720 

r? - @mozilla/fxa-devs

### CODE REVIEW

File: grunttasks/bump.js [hunk 1]
```diff
@@ -9,11 +9,11 @@
 module.exports = function (grunt) {
   grunt.config('bump', {
     options: {
-      files: ['package.json', 'npm-shrinkwrap.json'],
+      files: ['package.json', 'fxa-oauth-server/package.json', 'npm-shrinkwrap.json'],
```
Comment (philbooth) [inline grunttasks/bump.js]: Shouldn't we bump both shrinkwraps too?

Comment (jrgm) [reply grunttasks/bump.js]: Yeah, you're right. `__version__` looks at `package.json`, so solves the issue at hand, but bumping both is correct. I'll update.

**Comment by vladikoff** [comment]
@jrgm did you want this in train-124 or are you okay with the way it is live right now?
