### PR TITLE
fix(pool): Reject with an Error instance for HTTP errors.

### LINKED ISSUE #1590: An error from db-server instead cause hapi validation errors that uid was missing from response
The error from the db-server does not appear in the logs, so it is also eaten somewhere. If we want to deal with that separately, we can make a separate issue.

Here is the relevant log line:

```json
{
    "Timestamp": 1481582574987000000,
    "Logger": "fxa-auth-server",
    "Type": "request.summary",
    "Severity": 2,
    "Pid": 25262,
    "EnvVersion": "2.0",
    "Fields": {
        "op": "request.summary",
        "code": 500,
        "errno": 999,
        "rid": "1481582574980:ip-172-31-9-166:25262:ivo4etji:20017",
        "path": "/auth/v1/account/create",
        "lang": "en-US,en;q=0.5",
        "agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0",
        "remoteAddressChain": "[\"70.181.115.131\",\"172.31.13.228\",\"127.0.0.1\"]",
        "t": 7,
        "uid": "00",
        "service": "2651b9211a44b7b2",
        "email": "seantest12122016@mailinator.com",
        "stack": "Error: child \"uid\" fails because [\"uid\" is required]\n    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:201:26)\n    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)\n    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)\n at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:221:20)\n    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:86:16)\n at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:521:16)\n    at internals.Response._prepare.next [as _prepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:460:21)\n    at /data/fxa-auth-server/node_modules/hapi/lib/reply.js:152:22\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickDomainCallback (node.js:390:13)"
    }
}
```

### PR DESCRIPTION
**Pull request by rfk**
Fixes #1590.

### CODE REVIEW

File: lib/pool.js [hunk 1]
```diff
@@ -54,7 +54,14 @@ Pool.prototype.request = function (method, path, data) {
...
 
     if (res.statusCode < 200 || res.statusCode >= 300) {
-      var error = parsedBody || new Error(body)
+      var error = new Error()
+      if (! parsedBody) {
+        error.message = body
+      } else {
+        Object.keys(parsedBody).forEach(function(key) {
+          error[key] = parsedBody[key]
+        })
```
Comment (seanmonstar) [inline lib/pool.js]: Thanks nodejs upgrades, we can use `Object.assign(error, parsedBody)`!
