### PR TITLE
fix(push): Send push notification to devices when email has changed

### LINKED ISSUE #2017: Send "profile updated" push message when user changes primary email
To support the browser detecting the change, as discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1383663

### PR DESCRIPTION
**Pull request by vbudhram**
This PR Fixes #2017 and adds some extra change email coverage in local tests.

@mozilla/fxa-devs r?

### CODE REVIEW

File: test/local/routes/emails.js [hunk 1]
```diff
@@ -823,6 +823,66 @@ describe('/recovery_email', () => {
...
+          isVerified: false,
+          isPrimary: false
+        })
+      })
+
+      route = getRoute(accountRoutes, '/recovery_email/set_primary')
+      return runTest(route, mockRequest, () => {
+        assert.fail('Should have changing email')
+      })
+        .catch((err) => {
```
Comment (seanmonstar) [inline test/local/routes/emails.js]: This will technically catch the `assert.fail` from L878... it should then fail anyways, since an `AssertionError` shouldn't have `errno: 147`, but it's a dangerous pattern to have in tests. It's swallowed bugs before :_(

Something like this should work:

```js
return runTest(route, mockRequest)
  .then(
    () => assert.fail('should have errored')),
    err => assert.equal(err.errno, 147, 'correct errno changing email to unverified email')
  )
```

File: test/local/routes/emails.js [hunk 2]
```diff
@@ -823,6 +823,66 @@ describe('/recovery_email', () => {
...
+        return P.resolve({
+          uid: mockRequest.auth.credentials.uid,
+          isVerified: false,
+          isPrimary: false
+        })
+      })
+
+      route = getRoute(accountRoutes, '/recovery_email/set_primary')
+      return runTest(route, mockRequest, () => {
+        assert.fail('Should have changing email')
```
Comment (seanmonstar) [inline test/local/routes/emails.js]: Fail message reads oddly :)

File: lib/routes/emails.js [hunk 3]
```diff
@@ -767,6 +767,9 @@ module.exports = (log, db, mailer, config, customs, push) => {
 
               return db.setPrimaryEmail(uid, email.normalizedEmail)
             })
+            .then(() => {
+              push.notifyProfileUpdated(uid)
```
Comment (seanmonstar) [inline lib/routes/emails.js]: 👍

File: test/local/routes/emails.js (hunk 2 above)
Comment (vbudhram) [inline test/local/routes/emails.js]: Woops, meant to type `changed`.

**Comment by vbudhram** [comment]
Updated per @seanmonstar feedback, @mozilla/fxa-devs r?

File: test/local/routes/emails.js [hunk 4]
```diff
@@ -723,12 +723,9 @@ describe('/recovery_email', () => {
     it('should fail with unverified primary email', () => {
       route = getRoute(accountRoutes, '/recovery_email')
       mockRequest.auth.credentials.emailVerified = false
-      return runTest(route, mockRequest, () => {
-        assert.fail(new Error('Should have failed adding secondary email with unverified primary email'))
+      return runTest(route, mockRequest).then(() => assert.fail('Should have failed adding secondary email with unverified primary email'), err => {
+        assert.equal(err.errno, 104, 'unverified account')
```
Comment (philbooth) [inline test/local/routes/emails.js]: I'm bike-shedding, but I find the formatting here a little bit hard to read. Not sure if it would be cleaner if both promise handlers were on their own line?

**Comment by philbooth** [comment]
LGTM, r+
