### PR TITLE
fix(emails): fix arabic emails, add translator tests

### LINKED ISSUE #2714: Arabic emails not working
When I sign up in Russian, I receive the verification email in Russian. When I sign up in Arabic, I receive it in English. What gives?

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #2714

### CODE REVIEW

File: lib/senders/translator.js [hunk 1]
```diff
@@ -47,7 +47,15 @@ module.exports = function (locales, defaultLanguage) {
       var supportedLanguages = []
       for (var i = 0; i < translations.length; i++) {
         var t = translations[i]
-        var language = i18n.normalizeLanguage(i18n.languageFrom(t.locale_data.messages[''].lang))
+        const localeMessageData = t.locale_data.messages['']
+
+        if (localeMessageData.lang === 'ar') {
+          // NOTE: there seems to be some incompatibility with Jed and Arabic plural forms from Pontoon
```
Comment (vladikoff) [inline lib/senders/translator.js]: I spent too much time trying to find the incompatibility and it seems like this fix should suffice in the meantime

**Comment by shane-tomlinson** [comment]
I had a similar problem today when testing locally in Spanish. The initial email was sent in Spanish, but none of the subsequent emails were. Related?

**Comment by vladikoff** [comment]
> I had a similar problem today when testing locally in Spanish. The initial email was sent in Spanish, but none of the subsequent emails were. Related?

Should not be
