### PR TITLE
fix(logging): drop invalid metrics context data

### LINKED ISSUE #1540: Restrict allowed characters in metricsContext fields
Similar to https://github.com/mozilla/fxa-content-server/pull/4383, let's guard the integrity of our metrics data dumps by restricting the allowed characters in any of the metricsContext fields.  AFAICT there's no reason why any of them should allow characters beyond the basic alphanum and separator combos.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1540.

This changes adds regular expression for metrics context validation, mirroring the ones I'm adding to the content server in mozilla/fxa-content-server#4384. If anything violates a pattern we remove the metrics context data, which will prevent flow events from being emitted for those requests. This should reduce the corruption of flow event data that we see in redshift.

@seanmonstar r?

### CODE REVIEW

File: lib/metrics/context.js [hunk 1]
```diff
@@ -40,6 +40,14 @@ const NULL_MEMCACHED = {
   setAsync: NOP
 }
 
+const VALID_PROPERTIES = [
+  { key: 'context', pattern: /^[0-9a-z_-]+$/ },
+  { key: 'entrypoint', pattern: /^[\w\.-]+$/ },
+  { key: 'flowId', pattern: /^[0-9a-f]{64}$/ },
+  { key: 'migration', pattern: /^(sync11|amo)$/ },
+  { key: 'service', pattern: /^(sync|content-server|[0-9a-f]{16})$/ }
+]
```
Comment (seanmonstar) [inline lib/metrics/context.js]: 👍
