### PR TITLE
fix(push): do not throw if push fails on the notify endpoint

### LINKED ISSUE #1510: prod 500 errors on account/devices/notify for Fx51+
Noticed we're getting some 500's in prod like this:
```
"path":"/v1/account/devices/notify"
"agent":"Firefox-Android-FxAccounts/51.0a2 (Firefox)"
"stack":"Error: \"value\" must be an object
    at postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:201:26)
    at _validateWithOptions (/data/fxa-auth-server/node_modules/joi/lib/any.js:604:20)
    at root.validate (/data/fxa-auth-server/node_modules/joi/lib/index.js:105:23)
    at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:221:20)
    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)
    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)
    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16
    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:86:16)
    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at internals.Response._prepare.internals.Response._processPrepare.next [as _processPrepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:521:16)
    at internals.Response._prepare.next [as _prepare] (/data/fxa-auth-server/node_modules/hapi/lib/response.js:460:21)
    at /data/fxa-auth-server/node_modules/hapi/lib/reply.js:152:22
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)"}}
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1510

### CODE REVIEW

**Comment by vladikoff** [comment]
@rfk @seanmonstar  r?

File: lib/routes/account.js [hunk 1]
```diff
@@ -1201,12 +1201,25 @@ module.exports = function (
...
+            error: err
+          })
+        }
+
         return customs.checkAuthenticated(endpointAction, ip, stringUid)
           .then(function () {
             if (body.to === 'all') {
               return push.pushToAllDevices(uid, endpointAction, pushOptions)
+                .catch(catchPushError)
             } else {
```
Comment (seanmonstar) [inline lib/routes/account.js]: Promises kinda make you return from both clauses in many cases.

Comment (jrgm) [inline lib/routes/account.js]: True. But not here, right. (Anyways, not relevant to fixing the bug of course).

Comment (seanmonstar) [inline lib/routes/account.js]: It looks like it's needed to me. Based on the if, two different methods are called, both return a promise that needs to be returned as well.

File: lib/routes/account.js [hunk 2]
```diff
@@ -1201,12 +1201,25 @@ module.exports = function (
 
         var endpointAction = 'devicesNotify'
         var stringUid = uid.toString('hex')
+
+        function catchPushError(err) {
+          // push may fail due to not found devices or a bad push action
+          // log the error but still respond with a 200.
```
Comment (rfk) [inline lib/routes/account.js]: This is better than returning a 500, but would it be even more appropriate to return a 400 so that the client can know its request failed?
