### PR TITLE
fix(mailer): bring back process ports for mailer_server.js

### LINKED ISSUE #1814: Mailer config wants to bind to SMTP MTA host and port
https://github.com/mozilla/fxa-auth-server/commit/64c96d652f2096674d24832534e560fd5e30d462#commitcomment-21744769

https://github.com/mozilla/fxa-auth-server/blob/master/bin/mailer_server.js#L83-L90

Uh, this is wrong. smtp.port in auth-server is where an SMTP MTA is listening (port 25). Here, we attempt to bind the mailer_server.js daemon to that port, and in non-dev setup, die when we find out postfix is already there ;-). Or, alternatively, if not running as root or sudo, be denied the privilege of binding to port<1024.

And .env.dev saves dev from this, by changing SMTP_PORT to 9999.

Maybe add mailer.listen.host and mailer.listen.port (MAILER_LISTEN_HOST, MAILER_LISTEN_PORT) to ./config/index.js, and adjust tests as needed.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1814

@jrgm r?

### CODE REVIEW

File: config/index.js [hunk 1]
```diff
@@ -310,6 +310,18 @@ var conf = convict({
       }
     }
   },
+  mailerServer: {
+    host: {
+      doc: 'Host for mailer_server.js',
+      format: 'ipaddress',
+      default: '127.0.0.1'
```
Comment (jrgm) [inline config/index.js]: Doesn't matter now, but exposing a MAILER_LISTEN_HOST (or perhaps, MAILER_LISTEN_IP_ADDRESS) would be good.

Comment (vladikoff) [inline config/index.js]: Ok!

**Comment by vladikoff** [comment]
`MAILER_LISTEN_IP_ADDRESS` and `MAILER_LISTEN_PORT` for you!
