### PR TITLE
fix(sms): use a five minute period on polling

### LINKED ISSUE #2647: sms: it's quite common that when polling SMS budget, we fail to get an actual number
We're coming up on the budget limit, and should be stopping the use of SMS soon.

But since we're getting close, I've been looking at logs, and most of the polling gets a result with:

`{"op":"sms.budget.error","err":"Cannot read property 'Maximum' of undefined"}`

I have seen it succeed in some cases, and hopefully enough succeed to shut this down automatically in time. (If it looks like it's not going to be okay, I can roil a fix to disable this).

Anyways, this bug is to look at why we're failing as much as we are. (In comparison, using the aws-cli I always get a number back.)

### PR DESCRIPTION
**Pull request by jrgm**
I factored out the polling and ran it live. The granularity of data for this metric is 5 minutes, so using a 5 minute period and a starttime at least 5 minutes in the past always produces a result.

fixes #2647

r? - @philbooth

### CODE REVIEW

**Comment by jrgm** [comment]
I have to fix a test.

**Comment by jrgm** [comment]
Ok, fixed the test.

File: lib/senders/sms.js [hunk 1]
```diff
@@ -96,13 +97,13 @@ module.exports = (log, translator, templates, config) => {
         }
 
         const now = new Date()
-        const minuteAgo = new Date(now.getTime() - MILLISECONDS_PER_MINUTE)
+        const minuteAgo = new Date(now.getTime() - PERIOD_IN_MINUTES * MILLISECONDS_PER_MINUTE)
```
Comment (philbooth) [inline lib/senders/sms.js]: Tiny nit, but `minuteAgo` is a misleading name for this now. Either `fiveMinutesAgo`, or something along the lines of `startOfPeriod` if we don't want to hardcode the detail in the name, might be better?

Comment (jrgm) [reply lib/senders/sms.js]: good point

**Comment by philbooth** [comment]
> The granularity of data for this metric is 5 minutes, so using a 5 minute period and a starttime at least 5 minutes in the past always produces a result.

Ah, sorry about this. I remember reading a comment about it [in the docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html) and thought I'd understood, but scanning back now I clearly hadn't:

> For example, if you collect data using a period of 1 minute, the data remains available for 15 days with 1-minute resolution. After 15 days, this data is still available, but is aggregated and retrievable only with a resolution of 5 minutes.

**Comment by jrgm** [comment]
Updated, changing `minuteAgo` -> `startTime` and `now` -> `endTime`.

**Comment by jrgm** [comment]
> scanning back now I clearly hadn't

I'm still not sure I understand the text in the api docs, but this solution works for me!
