### PR TITLE
fix(devices): return the whole device record in POST /device response

### LINKED ISSUE #2130: POST /device endpoint should return the whole device record
Currently POST /device does not respect the API contract stating it [should return all fields for a device](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-body-4).
Instead this endpoint just echos back what was sent in the request body.
This is problematic because iOS is expecting the "type" field to be returned to every request (see https://github.com/mozilla-mobile/firefox-ios/pull/3201 for quickfix).

sessionToken [already contains the device record fields](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/devices-and-sessions.js#L119-L137), let's Object.assign() it for the update case.

### PR DESCRIPTION
**Pull request by eoger**
Fixes #2130

### CODE REVIEW

File: lib/routes/devices-and-sessions.js [hunk 1]
```diff
@@ -108,7 +108,17 @@ module.exports = (log, db, config, customs, push, devices) => {
...
+          .then(function (device) {
+            reply(Object.assign({}, {
+              id: sessionToken && sessionToken.deviceId,
+              name: sessionToken && sessionToken.deviceName,
+              type: sessionToken && sessionToken.deviceType,
+              pushCallback: sessionToken && sessionToken.callbackURL,
+              pushPublicKey: sessionToken && sessionToken.callbackPublicKey,
+              pushAuthKey: sessionToken && sessionToken.callbackAuthKey,
+              pushEndpointExpired: sessionToken && sessionToken.callbackIsExpired
+            }, device));
```
Comment (rfk) [inline lib/routes/devices-and-sessions.js]: This trailing semi is causing the linter to fail

**Comment by rfk** [comment]
@eoger thanks!  Could you please add a quick test for this as well?  It may be as simple as finding an existing test that does a partial device-record update, and asserting that additional fields are returned correctly.

**Comment by eoger** [comment]
Done thanks!
