### PR TITLE
fix(server): return sane user agent from /account/sessions

### LINKED ISSUE #1980: Logic for the userAgent property in /account/sessions is not sane and not tested
```
session.userAgent = (session.uaBrowser + ' ' + session.uaBrowserVersion).trim()
```

`uaBrowser` and `uaBrowserVersion` may be `null`, both together or independently. That causes us to display nonsense on the front-end. There are no tests to catch this behaviour.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1980.

I was in a bit of a funny mood on Friday and the `GET /account/sessions` endpoint in particular annoyed me for some reason. Hence this PR, which does the following:

* Fixes the `userAgent` property so that it is never `'null null'`.
* Makes the map function pure, so that the tests don't have to clone the mock db result.
* Adds assertions for some previously-untested behaviour.

@mozilla/fxa-devs r?

### CODE REVIEW

File: lib/routes/devices-sessions.js [hunk 1]
```diff
@@ -339,41 +339,41 @@ module.exports = (log, db, config, customs, push, devices) => {
...
+              if (! deviceName) {
+                deviceName = devices.synthesizeName(session)
               }
 
-              session.userAgent = (session.uaBrowser + ' ' + session.uaBrowserVersion).trim()
-
-              if (! session.deviceType) {
-                session.deviceType = session.uaDeviceType || 'desktop'
+              let userAgent
+              if (! session.uaBrowser) {
```
Comment (shane-tomlinson) [inline lib/routes/devices-sessions.js]: Yes!

File: lib/routes/devices-sessions.js [hunk 2]
```diff
@@ -339,41 +339,41 @@ module.exports = (log, db, config, customs, push, devices) => {
...
+                userAgent = ''
+              } else if (! session.uaBrowserVersion) {
+                userAgent = session.uaBrowser
```
Comment (shane-tomlinson) [inline lib/routes/devices-sessions.js]: I'm not sure what the reasons are on line 356 for trimming the result, does uaBrowser need to be trimmed to?

Comment (philbooth) [inline lib/routes/devices-sessions.js]: > I'm not sure what the reasons are on line 356 for trimming the result, does uaBrowser need to be trimmed to?

Actually the `trim()` is unnecessary now that we check whether `uaBrowser` and `uaBrowserVersion` before concatenating. Will remove it, thanks.

File: lib/routes/devices-sessions.js [hunk 3]
```diff
@@ -339,41 +339,41 @@ module.exports = (log, db, config, customs, push, devices) => {
...
+              let deviceName = session.deviceName
+              if (! deviceName) {
+                deviceName = devices.synthesizeName(session)
               }
 
-              session.userAgent = (session.uaBrowser + ' ' + session.uaBrowserVersion).trim()
-
-              if (! session.deviceType) {
-                session.deviceType = session.uaDeviceType || 'desktop'
+              let userAgent
```
Comment (vbudhram) [inline lib/routes/devices-sessions.js]: Is there any place where we log out the full and calculated user agent? Would be interesting to make a dashboard of this and back test that no funky values are being set.
