### PR TITLE
fix(config): Update secondary email config to support softvision and restmail

### LINKED ISSUE #1891: Update secondary email config to support @softvision / @restmail
Need to ungate that feature for those emails

### PR DESCRIPTION
**Pull request by vbudhram**
Found that softvision has `softvision.com`, `softvisioninc.eu`, `softvision.ro` emails. Updated regex to support this and `restmail.net`.

@vladikoff Does this match what you were expecting? . r?

Fixes #1891

### CODE REVIEW

File: config/index.js [hunk 1]
```diff
@@ -753,7 +753,7 @@ var conf = convict({
     enabledEmailAddresses: {
       doc: 'Only enable for email addresses matching this regex.',
       format: RegExp,
-      default: /.+@mozilla\.com$/,
+      default: /.+@mozilla\.com$|.+@restmail\.net$|.+@softvision\..{2,3}$/,
```
Comment (vladikoff) [inline config/index.js]: @vbudhram let's just write down `.com, .eu, .ro` here. Probably don't want any surprised coming from something like  `@softvision.ru`

**Comment by vladikoff** [comment]
Yay, thanks @vbudhram !
