### PR TITLE
fix(logging): account.verified & account.confirmed are mutually exclusive

### LINKED ISSUE #1415: Spurious account.confirmed activity event is emitted before account.verified
I just noticed this while working on something else. During the sign-up flow, immediately before the `account.verified` activity event, I saw this rogue `account.confirmed`.

```
activityEvent {"event":"account.confirmed","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0","service":"sync","uid":"85c9370f720c4d5996000d263c01f683"}
```

This event was only added recently in #1393, clearly I did it wrong.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #1415.

This eliminates the spurious logging of successful sign-in confirmation in the email verification case.

@vbudhram, should be exactly as we discussed in Vidyo, r?

### CODE REVIEW

File: lib/routes/account.js [hunk 1]
```diff
@@ -1263,6 +1263,7 @@ module.exports = function (
         db.account(uid)
           .then(
             function (account) {
+              var isEmailVerification = butil.buffersAreEqual(code, account.emailCode)
```
Comment (vbudhram) [inline lib/routes/account.js]: Something about `isEmailVerification` name seems a little misleading to me. Would `isAccountVerficiation` make more sense?

**Comment by vbudhram** [comment]
@philbooth Good catch! This looks like what we talked about. Up to you on the naming nit, I can see argument both ways, r+!
